apiVersion: v1
kind: ConfigMap
metadata:
  name: vector-haproxy
data:
  haproxy.cfg: |
    global
      log stdout format raw local0
      maxconn 4096
      stats socket /tmp/haproxy
      hard-stop-after 60s

    defaults
      log     global
      option  dontlognull
      retries 3
      option  redispatch
      option  allbackups
      timeout client 5s
      timeout server 5s
      timeout connect 5s

    resolvers coredns
      nameserver dns1 kube-dns.kube-system.svc.cluster.local:53
      resolve_retries 3
      timeout resolve 2s
      timeout retry 1s
      accepted_payload_size 8192
      hold valid 10s
      hold obsolete 60s

    frontend stats
      mode http
      bind :::1024
      option httplog
      http-request use-service prometheus-exporter if { path /metrics }

    frontend vector
      mode http
      bind :::8686 proto h2
      option httplog
      default_backend vector

    backend vector
      mode http
      balance roundrobin
      option tcp-check
      server-template srv 10 _vector._tcp.vector-aggregator-headless.default.svc.cluster.local resolvers coredns proto h2 check
