prometheus:
  prometheusSpec:
    additionalScrapeConfigs:
    - job_name: blackbox
      metrics_path: /probe
      params:
        module: [tcp_connect]
      static_configs:
      - targets: ["10.43.152.228:80","127.0.0.1:9090"]
      relabel_configs:
      - source_labels:
        - __address__
        target_label: instance
      - source_labels:
        - __address__
        target_label: __param_target
      - target_label: __address__
        replacement: prometheus-blackbox-exporter:9115
      - source_labels: [probe]
        action: keep
        regex: true
