vector:
  nameOverride: "vector-agent"
  fullnameOverride: "vector-agent"
  role: Agent
  logLevel: "info"
  podAnnotations:
    "prometheus.io/path": "/metrics"
    "prometheus.io/port": "9598"
    "prometheus.io/scrape": "true"
  containerPorts:
    - name: metrics
      containerPort: 9598
      protocol: TCP
    - name: api
      containerPort: 8686
      protocol: TCP
  customConfig:
    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: true
    sources:
      vector_monitoring:
        type: internal_metrics
      kubernetes_pod_logs:
        type: kubernetes_logs
        max_read_bytes: 100000
        ignore_older_secs: 86400 # ignore logs older than 1 day

    transforms:
      kubernetes_logs_timestamp_added:
        type: remap
        inputs:
          - kubernetes_pod_logs
        source: |-
          # add @timestamp field for calculate latency pipeline
          ."@timestamp"=.timestamp

    sinks:
      vector_aggregator:
        inputs:
          - kubernetes_pod_logs
        type: vector
        version: "2"
        address: vector-aggregator-haproxy.default.svc.cluster.local:6000
        batch:
          max_events: 128
        healthcheck:
          enabled: true
      victoria_metrics:
        type: prometheus_exporter
        inputs:
          - vector_monitoring
