vector:
  nameOverride: "vector-aggregator"
  fullnameOverride: "vector-aggregator"
  role: Aggregator
  resources:
    requests:
      cpu: 200m
      memory: 256Mi
    limits:
      cpu: 300m
      memory: 640Mi
  logLevel: "info"
  podAnnotations:
    prometheus.io/port: "9598"
    prometheus.io/scrape: "true"
  containerPorts:
    - name: api
      containerPort: 8686
      protocol: TCP
    - name: metrics
      containerPort: 9598
      protocol: TCP
  customConfig:
    data_dir: /vector-data-dir
    api:
      enabled: true
      address: 127.0.0.1:8686
      playground: true
    sources:
      vector:
        type: vector
        address: 0.0.0.0:6000
        version: "2"
    transforms:
      kubernetes_logs_mutate_fields:
        type: remap
        inputs:
          - vector
        source: |-
          log_message = .message

          # add lf_dc_name field from env var for all logs
          .lf_dc_name = get_env_var!("lf_dc_name")

          #TODO: mutations for modesecurity logs, is it still needed?
          if .kubernetes.pod_namespace == "ingress-nginx" && contains!(log_message, "modsecurity") {
              .waf = "modsecurity"
          }
    sinks:
      blackhole_aggregator:
        type: blackhole
        inputs:
          - vector
          # - <transform>
        print_interval_secs: 30
        rate: 100000
  extraContainers:
    - name: sleep
      image: busybox
      command:
        - "sh"
        - "-c"
        - "while true;do sleep 5; done"
  haproxy:
    enabled: true
    existingConfigMap: vector-aggregator-haproxy
    containerPorts:
      - name: vector
        containerPort: 6000
        protocol: TCP
    # extraContainers:
    #   - name: sleep
    #     image: busybox
    #     command:
    #       - "sh"
    #       - "-c"
    #       - "while true;do sleep 5; done"
    service:
      ports:
        - name: vector
          port: 6000
          protocol: TCP
          targetPort: 6000
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 100m
        memory: 128Mi
