apiVersion: v2
name: ingress-nginx
description: Umbrella Helm chart for ArgoCD app
type: application
version: 1.0.0
appVersion: "1.16.0"
dependencies:
- name: ingress-nginx
  version: 4.8.3
  repository: https://kubernetes.github.io/ingress-nginx
